## Importing Libraries

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introdcution to Tensor

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

In [6]:
scalar.ndim

1

In [ ]:
# Get tensor back as Python integer
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor

tensor = torch.tensor([[[1,2],
                        [3,5]],
                       [[1,2],
                       [4,5]],
                       [[2,3],
                        [1,77]]])

tensor

tensor([[[ 1,  2],
         [ 3,  5]],

        [[ 1,  2],
         [ 4,  5]],

        [[ 2,  3],
         [ 1, 77]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([3, 2, 2])

In [ ]:
tensor[2]

tensor([[ 2,  3],
        [ 1, 77]])

### Random Tensors

In [ ]:
## Random Tensors

rand_tensor = torch.randn(3,4,5)
rand_tensor

tensor([[[ 1.9193,  2.3893, -2.5218,  0.1974,  0.3708],
         [ 1.3506,  0.2806, -0.1132, -0.9658,  1.0566],
         [-0.4699,  0.3985,  0.1142, -0.4393,  0.9456],
         [ 0.3982, -0.4188, -2.5943,  0.0925,  1.7198]],

        [[-0.8735, -0.5378,  0.7587,  0.4664, -0.1596],
         [-0.3132,  1.2954, -1.2958,  1.2597,  0.2188],
         [-1.3432, -0.4004, -2.8116,  1.2350,  1.1006],
         [-0.1726, -0.1635,  0.2505, -0.0529,  1.3223]],

        [[-0.5657, -0.0488,  1.8151,  0.0516, -1.6804],
         [-2.2902, -1.0559, -0.2568,  1.6710, -0.7480],
         [ 0.1050, -1.3956,  0.9414, -0.3193,  0.2593],
         [ 0.8256,  0.7177, -1.2961,  0.7106,  0.6329]]])

In [ ]:
rand_tensor.ndim, rand_tensor.shape

(3, torch.Size([3, 4, 5]))

In [ ]:
# Random Tensors similar to image shape

rand_img_size_tensor = torch.randn(size=(3,224, 224)) #channel, height, width
rand_img_size_tensor.shape, rand_img_size_tensor.ndim, rand_img_size_tensor

(torch.Size([3, 224, 224]),
 3,
 tensor([[[-7.0905e-01,  1.3415e+00,  5.7346e-01,  ..., -4.2481e-01,
            1.2037e+00, -7.1751e-01],
          [ 1.3592e-01,  8.0005e-01, -1.2867e+00,  ..., -1.2638e+00,
           -1.6730e+00,  2.1777e-03],
          [-1.6202e+00, -1.0990e+00, -4.5709e-01,  ..., -8.5528e-01,
            6.1117e-01,  1.9387e-01],
          ...,
          [ 1.5980e+00, -2.1832e+00,  8.7935e-02,  ...,  1.2916e+00,
            2.5772e-01, -7.9948e-02],
          [ 1.5113e+00,  7.7558e-01,  5.5225e-01,  ..., -4.5091e-01,
            3.0639e-01,  8.3160e-01],
          [ 1.2788e-01, -5.8796e-02, -6.5201e-02,  ..., -2.2545e-01,
            1.0379e+00,  4.1787e-01]],
 
         [[ 1.0280e+00, -4.4828e-01, -1.1674e+00,  ...,  6.5749e-01,
           -8.7577e-01,  1.0332e-01],
          [ 4.4016e-01, -7.9866e-01, -1.1637e+00,  ..., -2.0660e-01,
            7.8788e-01, -1.8116e-01],
          [ 2.3109e-01,  5.3344e-01,  1.9132e+00,  ...,  9.7889e-01,
            7.7597e-01, -

In [ ]:
# Creating a tensor of all zeros

zeros = torch.zeros(size=(3,4,5))
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
zeros*rand_tensor

tensor([[[0., 0., -0., 0., 0.],
         [0., 0., -0., -0., 0.],
         [-0., 0., 0., -0., 0.],
         [0., -0., -0., 0., 0.]],

        [[-0., -0., 0., 0., -0.],
         [-0., 0., -0., 0., 0.],
         [-0., -0., -0., 0., 0.],
         [-0., -0., 0., -0., 0.]],

        [[-0., -0., 0., 0., -0.],
         [-0., -0., -0., 0., -0.],
         [0., -0., 0., -0., 0.],
         [0., 0., -0., 0., 0.]]])

In [ ]:
#Creating a tensor of all ones

ones = torch.ones(size=(3,4,5))
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
ones*rand_tensor

tensor([[[ 1.9193,  2.3893, -2.5218,  0.1974,  0.3708],
         [ 1.3506,  0.2806, -0.1132, -0.9658,  1.0566],
         [-0.4699,  0.3985,  0.1142, -0.4393,  0.9456],
         [ 0.3982, -0.4188, -2.5943,  0.0925,  1.7198]],

        [[-0.8735, -0.5378,  0.7587,  0.4664, -0.1596],
         [-0.3132,  1.2954, -1.2958,  1.2597,  0.2188],
         [-1.3432, -0.4004, -2.8116,  1.2350,  1.1006],
         [-0.1726, -0.1635,  0.2505, -0.0529,  1.3223]],

        [[-0.5657, -0.0488,  1.8151,  0.0516, -1.6804],
         [-2.2902, -1.0559, -0.2568,  1.6710, -0.7480],
         [ 0.1050, -1.3956,  0.9414, -0.3193,  0.2593],
         [ 0.8256,  0.7177, -1.2961,  0.7106,  0.6329]]])

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
## Creating tensors-like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensors

float_32_tensor = torch.tensor([3, 6 , 9], dtype=torch.float32,
                                                  device=None,
                                                  requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.int32)
float_16_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

In [ ]:
some_tensor = torch.randn(3,4)
some_tensor

tensor([[ 1.0010,  0.5118, -0.9905, -0.6376],
        [ 0.5928, -1.6763, -0.4554,  0.2547],
        [ 0.1784,  1.0073, -2.0234, -1.9675]])

In [ ]:
print(some_tensor)
print(f"Datatype of Tensor : {some_tensor.dtype}")
print(f"Shape of Tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[ 1.0010,  0.5118, -0.9905, -0.6376],
        [ 0.5928, -1.6763, -0.4554,  0.2547],
        [ 0.1784,  1.0073, -2.0234, -1.9675]])
Datatype of Tensor : torch.float32
Shape of Tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors

In [ ]:
tensor = torch.tensor([1,2,3], dtype=torch.float32)
tensor + 10

tensor([11., 12., 13.])

In [ ]:
tensor * 10

tensor([10., 20., 30.])

In [ ]:
tensor - 10

tensor([-9., -8., -7.])

In [ ]:
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [ ]:
torch.add(tensor,10)

tensor([11., 12., 13.])

In [ ]:
another_tensor = torch.randn(3,2)
another_tensor

tensor([[-1.0622,  1.5660],
        [-0.4899,  1.7938],
        [ 0.3232, -0.2706]])

Matrix Multiplication (Dot Product)

In [ ]:
# Element wise Multiplication

print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1., 2., 3.]) * tensor([1., 2., 3.])
Equals : tensor([1., 4., 9.])


In [ ]:
# Matrix Multiplication
%%time
torch.matmul(tensor, another_tensor)

CPU times: user 1.62 ms, sys: 970 µs, total: 2.59 ms
Wall time: 8.81 ms


tensor([-1.0724,  4.3416])

In [ ]:
%%time
tensor @ another_tensor

CPU times: user 87 µs, sys: 10 µs, total: 97 µs
Wall time: 113 µs


tensor([-1.0724,  4.3416])

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14.)
CPU times: user 562 µs, sys: 0 ns, total: 562 µs
Wall time: 590 µs


In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T) ##Transpose Tensor B (3 x 2) @ (2 x 3) = (3 x 3)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregation (Finding Max, Min, Mean, etc)

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find Min

torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
#Find Max

torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#Find Mean - torch.mean() can only get floating datatype

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum

torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of tensor where minimum occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> return index position of tensor where maximum occurs
x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
#Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

#Add an extra dim using unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.randn(size=(224,224,3)) #[height, width, channels]

#permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") #[channels, height, width]

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 903481
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(903481.), tensor(903481.))

## Indexing (selecting data from tensors)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Indexing the first dim
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Indexing the most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [ ]:
# Use ":" to select all of a target dimension

x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dim but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(f"Return 9: {x[0,2,2]}")

# Index on x to return 3,6,9
print(f"Return 3,6,9: {x[:,:,2]}")

Return 9: 9
Return 3,6,9: tensor([[3, 6, 9]])


## PyTorch Tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # converting from numpy array also uses the same dtype that numpy array uses which is float64 instead of tensor dtype of float32, use .type(torch.float32) to change the dtype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random )

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represenations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.





In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.randn(3,4)
random_tensor_B = torch.randn(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[ 0.3999, -1.6582,  0.1118, -1.8659],
        [-1.0140,  1.2440,  1.0176, -0.2798],
        [-0.4655, -1.7925,  0.5141,  0.4327]])
tensor([[ 2.1171, -0.6666,  0.6419, -1.1920],
        [-0.6016, -1.0138, -0.4305, -1.3184],
        [-0.4939,  1.1453,  1.0840, -0.0255]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Make some random but reproducible tensors
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# Keep in mind that `torch.manual_seed` needs to be redeclare if using a notebook, but usually it only needs to be declared once if using other IDE
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

In [ ]:
!nvidia-smi

Fri Jul 14 09:30:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting Tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (defualt on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU (NumPy can only uses CPU)

In [ ]:
#If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To Fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
import torch

In [ ]:
# Create random tensor with shape (7,7)
torch.rand(7,7)

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])