# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.8150, 0.2527, 0.4632, 0.3672, 0.7913, 0.5640, 0.2401],
        [0.6470, 0.5361, 0.7126, 0.1946, 0.4397, 0.1296, 0.1149],
        [0.6219, 0.5034, 0.0455, 0.9208, 0.2881, 0.4112, 0.5361],
        [0.5589, 0.7754, 0.3277, 0.8871, 0.5615, 0.6130, 0.5290],
        [0.7770, 0.3657, 0.3525, 0.0087, 0.9991, 0.4932, 0.9646],
        [0.9402, 0.2040, 0.8205, 0.1209, 0.1952, 0.0076, 0.4504],
        [0.8622, 0.6012, 0.4056, 0.7883, 0.0999, 0.2904, 0.0434]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
random_tensor = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor, random_tensor.T)

tensor([[1.6377],
        [1.5417],
        [1.3524],
        [1.6996],
        [1.6644],
        [1.6514],
        [1.6322]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [19]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_seed_A = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
random_seed_B = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(random_seed_A, random_seed_B.T), torch.matmul(random_seed_A, random_seed_B.T).shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [35]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(f"Device: {device}")

# Create two random tensors on GPU
torch.cuda.manual_seed(RANDOM_SEED)
random_gpu_A = torch.rand(2,3)
torch.cuda.manual_seed(RANDOM_SEED)
random_gpu_B = torch.rand(2,3)

#print(random_gpu_A, random_gpu_A.device)
#print(random_gpu_B, random_gpu_B.device)

random_to_gpu_A = random_gpu_A.to(device)
random_to_gpu_B = random_gpu_B.to(device)

print(random_to_gpu_A)
print(random_to_gpu_B)

Device: cuda
tensor([[0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300]], device='cuda:0')
tensor([[0.2560, 0.7366, 0.0204],
        [0.2036, 0.3748, 0.2564]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [40]:
# Perform matmul on tensor_A and tensor_B
matrix_mul = torch.matmul(random_to_gpu_A, random_to_gpu_B.T)
matrix_mul, matrix_mul.shape

(tensor([[0.4927, 0.4193],
         [0.6820, 0.5228]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [44]:
# Find max
print(f"Max Values: {matrix_mul.max()}")

# Find min
print(f"Min Values: {matrix_mul.min()}")

Max Values: 0.6820058822631836
Min Values: 0.41928476095199585


### 9. Find the maximum and minimum index values of the output of 7.

In [45]:
# Find arg max
print(f"Max Values: {matrix_mul.argmax()}")

# Find arg min
print(f"Min Values: {matrix_mul.argmin()}")

Max Values: 2
Min Values: 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [52]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
